# Generated by Django 3.2 on 2021-06-03 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='risk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.risk'),
        ),
    ]
