# Generated by Django 3.2 on 2021-06-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210604_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fastSelling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
