# Generated by Django 3.2 on 2021-06-04 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210604_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Watering',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.watering'),
        ),
        migrations.AddField(
            model_name='product',
            name='sun',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.sun'),
        ),
    ]
