# Generated by Django 3.2 on 2021-06-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210604_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='fastSelling',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer',
        ),
    ]
