# Generated by Django 3.2 on 2021-06-04 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210604_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='saleprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.tag'),
        ),
    ]
