# Generated by Django 3.2 on 2021-06-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210604_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='saleprice',
            new_name='orgprice',
        ),
    ]
