# Generated by Django 3.2 on 2021-06-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20210606_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mother',
            field=models.BooleanField(default=False),
        ),
    ]
