# Generated by Django 3.2 on 2021-06-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_mother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Nickname',
            field=models.CharField(max_length=255),
        ),
    ]
